---
abstract: 'an Altogether Lovely Internet Chatting Experience'
author:
  - 'Lee Aylward <leedo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.86
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Alice
no_index:
  directory:
    - inc
    - share
    - share/sprockets
    - t
requires:
  AnyEvent: 5.2
  AnyEvent::HTTP: 0
  AnyEvent::HTTPD: 0
  AnyEvent::IRC: 0.95
  Digest::CRC: 0.14
  File::ShareDir: 0.01
  IRC::Formatting::HTML: 0.08
  JSON: 2.12
  Moose: 0.90
  Text::MicroTemplate: 0.09
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
